### ISSUE TITLE
Uncaught Error: Cannot find module './Models/video'

### ISSUE THREAD

**Issue by eckucukoglu** [Hatisoft/playyoutube-atom#10]
It happens during installation.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [playyoutube](https://github.com/Hatisoft/playyoutube-atom) package 2.0.2

### Stack Trace

Uncaught Error: Cannot find module './Models/video'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module './Models/video'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/playyoutube/lib/playyoutube-atom.js:7:51)
    at /packages/playyoutube/lib/playyoutube-atom.js:137:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688211)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3218243)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3207531)
    at PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:933491)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2612928)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2603208)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2603031)
    at /usr/share/atom/resources/app/static/<embedded>:14:2611161
    at /usr/share/atom/resources/app/static/<embedded>:14:2613179
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1213350)
    at PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:942948)
    at /usr/share/atom/resources/app/static/<embedded>:11:940080
    at r (/usr/share/atom/resources/app/static/<embedded>:11:934610)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1128169)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1128323)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1126925)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
```

### Non-Core Packages

```
aesthetic-ui 4.0.0 
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-package-sync 0.4.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
cake-syntax 1.0.2 
chester-atom-syntax 0.3.2 
eclipse-keybindings 0.9.0 
file-icons 2.1.36 
highlight-line 0.12.0 
highlight-selected 0.16.0 
intentions 1.1.5 
isotope-light-ui 2.3.0 
isotope-ui 2.8.5 
linter 2.3.1 
linter-pycodestyle 2.1.3 
linter-ui-default 1.8.0 
markdown-preview-plus 3.11.5 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-split-diff 0.3.7 
native-ui 0.27.0 
pen-paper-coffee-syntax 0.17.0 
playyoutube 2.0.2 
pretty-json 2.1.2 
railscast-theme 0.4.0 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
yeti-ui 0.1.6 
```

**Comment by alvarolorentedev** [comment]
thanks will have a look, seems to be an issue with capitals, not sure how i made that mistake :(

**Comment by alvarolorentedev** [comment]
@eckucukoglu if you can try again it should be solved. Sorry i did not noticed the issue with the cases, as i developed it in windows at that point (strange i was also using it in mac that should be case sensitive).

**Comment by eckucukoglu** [comment]
hi kanekotic,

unfortunately, it is still not working. I can make search, but nothing happens when I choose one from results. Also I needed to try several times hide-cancel until the player opens. i didn't use the keybindings btw.

sorry but you seriously need to test this on linux. it seems there are still some bugs in it.

**Comment by alvarolorentedev** [comment]
ok. I will take some days to undust my linux computer and debug this, having a look. Thanks for trying it.

**Comment by alvarolorentedev** [comment]
btw @eckucukoglu, if you can do just a small test, as i think it might be just a documentation issue (pluss a not to user friendly stuff).
When you go up an down on the list (as it seems that is working) to play a vieo you have to use the left or right arrow (as enter is used to search).
This is really not intuitive so i will do some work to improve.

**Comment by eckucukoglu** [comment]
now it worked. however this time, none of the videos are working. Youtube returns "Video unavailable".
Btw, if I accidentally click smth in pop-up, then it opens another one; which can't be closed by **close** command.

good luck. :)

**Comment by alvarolorentedev** [comment]
thanks for all the useful info. I will have a look. If its not to much asking what did you search and what video failed (that will help me get an example, of what is failing).
Youtube in some cases is super absurd as it lets you search some videos but when adding them on the player it says they are not playable due restrictions, i wanted to see if there was a way to filter those videos but for now i was not lucky to do it (I might give it another try).

**Comment by eckucukoglu** [comment]
pagan poetry bjork and tried to open 2-3 of them. also cascade siouxsie, then same.

**Comment by alvarolorentedev** [comment]
I will have a look but i feel is part of what youtube blocks on playing out of their page some licensed stuff, will double check if i can configure or get a diferent player that solves that.

**Comment by eckucukoglu** [comment]
Good luck. :) Since this issue is now solved, I am closing it.
